// Generated by view binder compiler. Do not edit!
package com.project.engg.movieticketbooking.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.project.engg.movieticketbooking.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityMtbRegisterBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button bsave;

  @NonNull
  public final ImageView imgpicture;

  @NonNull
  public final EditText taddress;

  @NonNull
  public final EditText tmobno;

  @NonNull
  public final EditText tname;

  private ActivityMtbRegisterBinding(@NonNull ConstraintLayout rootView, @NonNull Button bsave,
      @NonNull ImageView imgpicture, @NonNull EditText taddress, @NonNull EditText tmobno,
      @NonNull EditText tname) {
    this.rootView = rootView;
    this.bsave = bsave;
    this.imgpicture = imgpicture;
    this.taddress = taddress;
    this.tmobno = tmobno;
    this.tname = tname;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMtbRegisterBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMtbRegisterBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_mtb_register, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMtbRegisterBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.bsave;
      Button bsave = ViewBindings.findChildViewById(rootView, id);
      if (bsave == null) {
        break missingId;
      }

      id = R.id.imgpicture;
      ImageView imgpicture = ViewBindings.findChildViewById(rootView, id);
      if (imgpicture == null) {
        break missingId;
      }

      id = R.id.taddress;
      EditText taddress = ViewBindings.findChildViewById(rootView, id);
      if (taddress == null) {
        break missingId;
      }

      id = R.id.tmobno;
      EditText tmobno = ViewBindings.findChildViewById(rootView, id);
      if (tmobno == null) {
        break missingId;
      }

      id = R.id.tname;
      EditText tname = ViewBindings.findChildViewById(rootView, id);
      if (tname == null) {
        break missingId;
      }

      return new ActivityMtbRegisterBinding((ConstraintLayout) rootView, bsave, imgpicture,
          taddress, tmobno, tname);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
