// Generated by view binder compiler. Do not edit!
package com.project.engg.movieticketbooking.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageButton;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import android.widget.Spinner;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.project.engg.movieticketbooking.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityMtbBookingBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button bsend;

  @NonNull
  public final ImageButton btbdate;

  @NonNull
  public final ImageView imgpicture;

  @NonNull
  public final RelativeLayout rlsname;

  @NonNull
  public final RelativeLayout rltbdate;

  @NonNull
  public final Spinner sname;

  @NonNull
  public final EditText tamt;

  @NonNull
  public final EditText tbdate;

  @NonNull
  public final EditText tbdetails;

  @NonNull
  public final EditText tdetails;

  @NonNull
  public final EditText tname;

  @NonNull
  public final EditText tprice;

  @NonNull
  public final EditText tseating;

  @NonNull
  public final EditText ttno;

  private ActivityMtbBookingBinding(@NonNull ConstraintLayout rootView, @NonNull Button bsend,
      @NonNull ImageButton btbdate, @NonNull ImageView imgpicture, @NonNull RelativeLayout rlsname,
      @NonNull RelativeLayout rltbdate, @NonNull Spinner sname, @NonNull EditText tamt,
      @NonNull EditText tbdate, @NonNull EditText tbdetails, @NonNull EditText tdetails,
      @NonNull EditText tname, @NonNull EditText tprice, @NonNull EditText tseating,
      @NonNull EditText ttno) {
    this.rootView = rootView;
    this.bsend = bsend;
    this.btbdate = btbdate;
    this.imgpicture = imgpicture;
    this.rlsname = rlsname;
    this.rltbdate = rltbdate;
    this.sname = sname;
    this.tamt = tamt;
    this.tbdate = tbdate;
    this.tbdetails = tbdetails;
    this.tdetails = tdetails;
    this.tname = tname;
    this.tprice = tprice;
    this.tseating = tseating;
    this.ttno = ttno;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMtbBookingBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMtbBookingBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_mtb_booking, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMtbBookingBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.bsend;
      Button bsend = ViewBindings.findChildViewById(rootView, id);
      if (bsend == null) {
        break missingId;
      }

      id = R.id.btbdate;
      ImageButton btbdate = ViewBindings.findChildViewById(rootView, id);
      if (btbdate == null) {
        break missingId;
      }

      id = R.id.imgpicture;
      ImageView imgpicture = ViewBindings.findChildViewById(rootView, id);
      if (imgpicture == null) {
        break missingId;
      }

      id = R.id.rlsname;
      RelativeLayout rlsname = ViewBindings.findChildViewById(rootView, id);
      if (rlsname == null) {
        break missingId;
      }

      id = R.id.rltbdate;
      RelativeLayout rltbdate = ViewBindings.findChildViewById(rootView, id);
      if (rltbdate == null) {
        break missingId;
      }

      id = R.id.sname;
      Spinner sname = ViewBindings.findChildViewById(rootView, id);
      if (sname == null) {
        break missingId;
      }

      id = R.id.tamt;
      EditText tamt = ViewBindings.findChildViewById(rootView, id);
      if (tamt == null) {
        break missingId;
      }

      id = R.id.tbdate;
      EditText tbdate = ViewBindings.findChildViewById(rootView, id);
      if (tbdate == null) {
        break missingId;
      }

      id = R.id.tbdetails;
      EditText tbdetails = ViewBindings.findChildViewById(rootView, id);
      if (tbdetails == null) {
        break missingId;
      }

      id = R.id.tdetails;
      EditText tdetails = ViewBindings.findChildViewById(rootView, id);
      if (tdetails == null) {
        break missingId;
      }

      id = R.id.tname;
      EditText tname = ViewBindings.findChildViewById(rootView, id);
      if (tname == null) {
        break missingId;
      }

      id = R.id.tprice;
      EditText tprice = ViewBindings.findChildViewById(rootView, id);
      if (tprice == null) {
        break missingId;
      }

      id = R.id.tseating;
      EditText tseating = ViewBindings.findChildViewById(rootView, id);
      if (tseating == null) {
        break missingId;
      }

      id = R.id.ttno;
      EditText ttno = ViewBindings.findChildViewById(rootView, id);
      if (ttno == null) {
        break missingId;
      }

      return new ActivityMtbBookingBinding((ConstraintLayout) rootView, bsend, btbdate, imgpicture,
          rlsname, rltbdate, sname, tamt, tbdate, tbdetails, tdetails, tname, tprice, tseating,
          ttno);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
