// Generated by view binder compiler. Do not edit!
package com.project.engg.movieticketbooking.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.project.engg.movieticketbooking.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityMainBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ConstraintLayout mainLayout;

  @NonNull
  public final TextView tv1;

  @NonNull
  public final TextView tv2;

  @NonNull
  public final TextView tv3;

  @NonNull
  public final TextView tv4;

  @NonNull
  public final TextView tv5;

  @NonNull
  public final TextView tv7;

  @NonNull
  public final TextView tv8;

  @NonNull
  public final TextView tv9;

  private ActivityMainBinding(@NonNull ConstraintLayout rootView,
      @NonNull ConstraintLayout mainLayout, @NonNull TextView tv1, @NonNull TextView tv2,
      @NonNull TextView tv3, @NonNull TextView tv4, @NonNull TextView tv5, @NonNull TextView tv7,
      @NonNull TextView tv8, @NonNull TextView tv9) {
    this.rootView = rootView;
    this.mainLayout = mainLayout;
    this.tv1 = tv1;
    this.tv2 = tv2;
    this.tv3 = tv3;
    this.tv4 = tv4;
    this.tv5 = tv5;
    this.tv7 = tv7;
    this.tv8 = tv8;
    this.tv9 = tv9;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_main, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMainBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      ConstraintLayout mainLayout = (ConstraintLayout) rootView;

      id = R.id.tv1;
      TextView tv1 = ViewBindings.findChildViewById(rootView, id);
      if (tv1 == null) {
        break missingId;
      }

      id = R.id.tv2;
      TextView tv2 = ViewBindings.findChildViewById(rootView, id);
      if (tv2 == null) {
        break missingId;
      }

      id = R.id.tv3;
      TextView tv3 = ViewBindings.findChildViewById(rootView, id);
      if (tv3 == null) {
        break missingId;
      }

      id = R.id.tv4;
      TextView tv4 = ViewBindings.findChildViewById(rootView, id);
      if (tv4 == null) {
        break missingId;
      }

      id = R.id.tv5;
      TextView tv5 = ViewBindings.findChildViewById(rootView, id);
      if (tv5 == null) {
        break missingId;
      }

      id = R.id.tv7;
      TextView tv7 = ViewBindings.findChildViewById(rootView, id);
      if (tv7 == null) {
        break missingId;
      }

      id = R.id.tv8;
      TextView tv8 = ViewBindings.findChildViewById(rootView, id);
      if (tv8 == null) {
        break missingId;
      }

      id = R.id.tv9;
      TextView tv9 = ViewBindings.findChildViewById(rootView, id);
      if (tv9 == null) {
        break missingId;
      }

      return new ActivityMainBinding((ConstraintLayout) rootView, mainLayout, tv1, tv2, tv3, tv4,
          tv5, tv7, tv8, tv9);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
