// Generated by view binder compiler. Do not edit!
package com.project.engg.movieticketbooking.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.project.engg.movieticketbooking.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityMtbLoginBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button blogin;

  @NonNull
  public final Button bregister;

  @NonNull
  public final ImageView imgpicture;

  @NonNull
  public final EditText tmobno;

  private ActivityMtbLoginBinding(@NonNull ConstraintLayout rootView, @NonNull Button blogin,
      @NonNull Button bregister, @NonNull ImageView imgpicture, @NonNull EditText tmobno) {
    this.rootView = rootView;
    this.blogin = blogin;
    this.bregister = bregister;
    this.imgpicture = imgpicture;
    this.tmobno = tmobno;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMtbLoginBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMtbLoginBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_mtb_login, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMtbLoginBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.blogin;
      Button blogin = ViewBindings.findChildViewById(rootView, id);
      if (blogin == null) {
        break missingId;
      }

      id = R.id.bregister;
      Button bregister = ViewBindings.findChildViewById(rootView, id);
      if (bregister == null) {
        break missingId;
      }

      id = R.id.imgpicture;
      ImageView imgpicture = ViewBindings.findChildViewById(rootView, id);
      if (imgpicture == null) {
        break missingId;
      }

      id = R.id.tmobno;
      EditText tmobno = ViewBindings.findChildViewById(rootView, id);
      if (tmobno == null) {
        break missingId;
      }

      return new ActivityMtbLoginBinding((ConstraintLayout) rootView, blogin, bregister, imgpicture,
          tmobno);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
